if(NOT DEFINED TEXUTIL OR NOT DEFINED WORK)
  message(FATAL_ERROR "TEXUTIL and WORK are required")
endif()
file(MAKE_DIRECTORY "${WORK}")
file(WRITE "${WORK}/graph.json" [=[{"size":32,"nodes":{"a":{"op":"constant","value":0.5},"n":{"op":"normal","input":"a"}},"outputs":{"height":{"node":"a","bits":16},"normal.png":"n"}}]=])
execute_process(COMMAND "${TEXUTIL}" "${WORK}/graph.json" --size 17x9 --seed 5 --out "${WORK}/output" --threads 2 --json RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Render failed: ${error}")
endif()
string(JSON width GET "${output}" size 0)
string(JSON height GET "${output}" size 1)
string(JSON seed GET "${output}" seed)
if(NOT width EQUAL 17 OR NOT height EQUAL 9 OR NOT seed EQUAL 5)
  message(FATAL_ERROR "CLI overrides were not applied")
endif()
file(READ "${WORK}/output/height.png" png LIMIT 26 HEX)
if(NOT png STREQUAL "89504e470d0a1a0a0000000d4948445200000011000000091000")
  message(FATAL_ERROR "Expected 17x9 16-bit grayscale PNG header, got ${png}")
endif()
execute_process(COMMAND "${TEXUTIL}" render - --out "${WORK}/stdin" INPUT_FILE "${WORK}/graph.json" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Stdin render failed: ${error}")
endif()
execute_process(COMMAND "${TEXUTIL}" "${WORK}/graph.json" --wat RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "unknown option")
  message(FATAL_ERROR "Unknown CLI option was not rejected")
endif()
execute_process(COMMAND "${TEXUTIL}" validate "${WORK}/graph.json" --json RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "JSON validation failed")
endif()
string(JSON reachable GET "${output}" reachable)
if(NOT reachable EQUAL 2)
  message(FATAL_ERROR "Unexpected validation result")
endif()
execute_process(COMMAND "${TEXUTIL}" describe ramp RESULT_VARIABLE result OUTPUT_VARIABLE output)
string(JSON interpolation GET "${output}" parameters interpolation default)
if(NOT result EQUAL 0 OR NOT interpolation STREQUAL "linear")
  message(FATAL_ERROR "Node discovery failed")
endif()
file(APPEND "${WORK}/graph.json" " trailing garbage")
execute_process(COMMAND "${TEXUTIL}" validate "${WORK}/graph.json" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "parse_error")
  message(FATAL_ERROR "Trailing JSON data was not rejected")
endif()
