file(GLOB graphs "${SOURCE}/samples/*.json")
foreach(graph IN LISTS graphs)
  get_filename_component(name "${graph}" NAME)
  execute_process(COMMAND "${TEXUTIL}" validate "${graph}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Sample ${name}: ${error}")
  endif()
  if(EXISTS "${SOURCE}/examples/${name}")
    file(SHA256 "${graph}" sample_hash)
    file(SHA256 "${SOURCE}/examples/${name}" example_hash)
    if(NOT sample_hash STREQUAL example_hash)
      message(FATAL_ERROR "Sample ${name} diverged from examples/${name}; update both copies intentionally.")
    endif()
  endif()
endforeach()
execute_process(COMMAND "${TEXUTIL}" "${SOURCE}/samples/terrain.json" --size 64 --out "${WORK}/terrain" --threads 2 --json RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Terrain sample render: ${error}")
endif()
