#!/usr/bin/env python3
"""Regenerate the node reference from the executable's authoritative catalog."""
import json
import pathlib
import subprocess
import sys

root = pathlib.Path(__file__).resolve().parents[1]
binary = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else root / 'build/texutil'
catalog = json.loads(subprocess.check_output([str(binary), 'nodes', '--json']))
lines = ['# Node reference', '', 'Generated by `python3 tools/update_docs.py` from `texutil nodes --json`.', '',
         'Every node requires `op`. Inputs are node names. Unknown parameters and invalid',
         'values are errors. `null` in the default column means omitted, not JSON null.',
         'Required fields must be supplied. See [README](../README.md) for coordinate,',
         'alpha, data, color-space, and tiling conventions.', '']
for name, spec in catalog.items():
    lines += ['## ' + name, '', spec['description'], '', '| Parameter | Type | Default | Options / bounds | Meaning |', '| --- | --- | --- | --- | --- |']
    for name, param in spec['parameters'].items():
        default = '**required**' if param.get('required') else '`' + json.dumps(param.get('default'), separators=(',', ':')) + '`'
        bounds = ', '.join('`' + str(value) + '`' for value in param.get('enum', []))
        if 'min' in param:
            bounds = str(param['min']) + '..' + str(param['max'])
        lines.append('| `' + name + '` | ' + param['type'] + ' | ' + default + ' | ' + bounds + ' | ' + param['description'].replace('|', '\\|') + ' |')
    lines.append('')
(root / 'docs/NODES.md').write_text('\n'.join(lines) + '\n')
(root / 'docs/nodes.json').write_text(json.dumps(catalog, indent=2) + '\n')
print('Updated docs/NODES.md and docs/nodes.json')
