set(TEXUTIL_FILAMENT_ROOT "" CACHE PATH "Filament SDK directory (matching matc and runtime)")
if(TEXUTIL_FILAMENT_ROOT)
  # Filament 1.76 public headers require C++20; CPU-only builds remain C++17.
  set_property(TARGET texutil_core PROPERTY CXX_STANDARD 20)
  if(APPLE)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
      set(filament_arch arm64)
    else()
      set(filament_arch x86_64)
    endif()
  elseif(WIN32)
    set(filament_arch x86_64/md)
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
    set(filament_arch aarch64)
  else()
    set(filament_arch x86_64)
  endif()
  set(filament_lib "${TEXUTIL_FILAMENT_ROOT}/lib/${filament_arch}")
  find_program(TEXUTIL_MATC matc PATHS "${TEXUTIL_FILAMENT_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
  foreach(name filament backend filabridge filaflat utils geometry mikktspace smol-v shaders filament-iblprefilter filament-generatePrefilterMipmap)
    find_library(TEXUTIL_FILAMENT_${name} NAMES ${name} PATHS "${filament_lib}" NO_DEFAULT_PATH REQUIRED)
    target_link_libraries(texutil_core PRIVATE "${TEXUTIL_FILAMENT_${name}}")
  endforeach()
  # Desktop platform dependencies vary between official SDK releases.
  foreach(name abseil bluegl bluevk zstd)
    find_library(TEXUTIL_FILAMENT_${name} NAMES ${name} PATHS "${filament_lib}" NO_DEFAULT_PATH)
    if(TEXUTIL_FILAMENT_${name})
      target_link_libraries(texutil_core PRIVATE "${TEXUTIL_FILAMENT_${name}}")
    endif()
  endforeach()
  if(APPLE)
    target_link_libraries(texutil_core PRIVATE "-framework Cocoa" "-framework Metal" "-framework CoreVideo" "-framework QuartzCore" "-framework IOKit")
  elseif(WIN32)
    target_link_libraries(texutil_core PRIVATE opengl32 gdi32 user32 shlwapi)
  else()
    target_link_libraries(texutil_core PRIVATE dl)
  endif()
  target_include_directories(texutil_core SYSTEM PRIVATE "${TEXUTIL_FILAMENT_ROOT}/include")
  target_compile_definitions(texutil_core PRIVATE TEXUTIL_HAS_FILAMENT=1 TEXUTIL_ASSET_DIR="${CMAKE_CURRENT_SOURCE_DIR}/assets/hdri")
  foreach(variant solid thin opaque)
    if(variant STREQUAL "thin")
      set(thin_define 1)
    else()
      set(thin_define 0)
    endif()
    if(variant STREQUAL "opaque")
      set(refraction_define 0)
      set(refraction_mode none)
      set(refraction_type solid)
    else()
      set(refraction_define 1)
      set(refraction_mode screenspace)
      set(refraction_type ${variant})
    endif()
    set(binary "${CMAKE_CURRENT_BINARY_DIR}/preview-${variant}.filamat")
    set(header "${CMAKE_CURRENT_BINARY_DIR}/generated/preview_${variant}.h")
    add_custom_command(OUTPUT "${header}"
      COMMAND "${TEXUTIL_MATC}" -p desktop -a all -S -DTEXUTIL_THIN=${thin_define} -DTEXUTIL_REFRACT=${refraction_define} -PrefractionType=${refraction_type} -PrefractionMode=${refraction_mode} -o "${binary}" "${CMAKE_CURRENT_SOURCE_DIR}/src/materials/preview.mat"
      COMMAND "${CMAKE_COMMAND}" -DINPUT=${binary} -DOUTPUT=${header} -DSYMBOL=preview_${variant} -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedBinary.cmake"
      DEPENDS src/materials/preview.mat cmake/EmbedBinary.cmake VERBATIM)
    target_sources(texutil_core PRIVATE "${header}")
  endforeach()
  target_include_directories(texutil_core PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated")
  message(STATUS "TexUtil: Filament mesh previews enabled")
else()
  message(STATUS "TexUtil: CPU model operations enabled; set TEXUTIL_FILAMENT_ROOT for previews")
endif()
install(DIRECTORY assets/hdri DESTINATION share/texutil)

install(DIRECTORY docs/licenses DESTINATION share/texutil)
install(FILES LICENSE docs/THIRD_PARTY.md DESTINATION share/texutil)
